language: groovy

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7

env:
  matrix:
    - MODULE=contracto-retrofit
    - MODULE=contracto-spring


before_script:
  - scripts/run_http_server &

script:
  - ./gradlew :$MODULE:test
